#define GxEPD2_DISPLAY_CLASS GxEPD2_BW
#define GxEPD2_DRIVER_CLASS GxEPD2_270
// pin definitions
#ifdef ESP32
// this is the VSPI on the ESP32
#define EPD_CS 5
#define EPD_DC 19
#define EPD_RST 22
#define EPD_BUSY 21
#endif

#ifdef ESP8266
#define EPD_CS D8
#define EPD_DC D3
#define EPD_RST D1
#define EPD_BUSY D4
#endif


#define MAX_DISPLAY_BUFFER_SIZE 65536UL
#define MAX_HEIGHT(EPD) (EPD::HEIGHT <= (MAX_DISPLAY_BUFFER_SIZE) / (EPD::WIDTH / 2) ? EPD::HEIGHT : (MAX_DISPLAY_BUFFER_SIZE) / (EPD::WIDTH / 2))
GxEPD2_DISPLAY_CLASS<GxEPD2_DRIVER_CLASS, MAX_HEIGHT(GxEPD2_DRIVER_CLASS)> display(GxEPD2_DRIVER_CLASS(EPD_CS, EPD_DC, EPD_RST, EPD_BUSY));
#undef MAX_DISPLAY_BUFFER_SIZE
#undef MAX_HEIGHT
